{
 "title": "Tvheadned",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "decoder",
    "label": "decoder",
    "query": {
     "query": "label_values(tvheadend_decoder_last_update,decoder)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Signal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Signal",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "tvheadend_decoder_signal{decoder=~\"$decoder\"}/1000 != 0",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"signal\")\n"
    }
   ]
  },
  {
   "title": "Signal to Noise Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "tvheadend_decoder_snr{decoder=~\"$decoder\"}/1000 != 0",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"snr\")\n"
    }
   ]
  },
  {
   "title": "BPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "tvheadend_decoder_bps{decoder=~\"$decoder\"}/1000 != 0",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"bps\")\n"
    }
   ]
  },
  {
   "title": "Bit Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "tvheadend_decoder_ber{decoder=~\"$decoder\"}",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"ber\")\n"
    }
   ]
  },
  {
   "title": "Uncorrected Blocks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(tvheadend_decoder_unc{decoder=~\"$decoder\"}[$__rate_interval])",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"unc\")\n"
    }
   ]
  },
  {
   "title": "Transport Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(tvheadend_decoder_te{decoder=~\"$decoder\"}[$__rate_interval])",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"te\")\n"
    }
   ]
  },
  {
   "title": "Continuity Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(tvheadend_decoder_cc{decoder=~\"$decoder\"}[$__rate_interval])",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"cc\")\n"
    }
   ]
  },
  {
   "title": "EC bit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "tvheadend_decoder_ec_bit{decoder=~\"$decoder\"}",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"ec_bit\")\n"
    }
   ]
  },
  {
   "title": "TC bit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "tvheadend_decoder_tc_bit{decoder=~\"$decoder\"}",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"tc_bit\")\n"
    }
   ]
  },
  {
   "title": "EC block",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(tvheadend_decoder_ec_block{decoder=~\"$decoder\"}[$__rate_interval])",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"ec_block\")\n"
    }
   ]
  },
  {
   "title": "TC block",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "tvheadend_decoder_tc_block{decoder=~\"$decoder\"}",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"tc_block\")\n"
    }
   ]
  },
  { "title": "Subscribing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Subscribers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "tvheadend_decoder_subs{decoder=~\"$decoder\"}",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"subs\")\n"
    }
   ]
  },
  {
   "title": "Weight",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "tvheadend_decoder_weight{decoder=~\"$decoder\"}",
     "legendFormat": "{{decoder}}",
     "query": "from(bucket: \"tv\")\n    |> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn:(r) => r._measurement == \"tv-status\")\n    |> filter(fn: (r) => r[\"decoder\"] == \"${decoder}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"weight\")\n"
    }
   ]
  }
 ]
}